---
"AWSTemplateFormatVersion": "2010-09-09"

Parameters:
  LinuxAmi:
    Type: String

Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        KeyName: allenF_2022_07_05
        InstanceType: t2.small
        ImageId: !Ref LinuxAmi
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: user
                Value: allen.fisher
              - Key: "stelligent-u-lesson"
                Value: "6"

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AutoScalingGroupName: "AllenFModule612ASG"
      AvailabilityZones:
        - "us-west-1a"
      MaxSize: "1"
      MinSize: "1"
      DesiredCapacity: "1"
      VPCZoneIdentifier: 
        - !ImportValue AllenModule08PrivateSubnetId
      LaunchTemplate:
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
        LaunchTemplateId: !Ref MyLaunchTemplate
      Tags:
        - Key: user
          Value: allen.fisher
          PropagateAtLaunch: true
        - Key: "stelligent-u-lesson"
          Value: "6"
          PropagateAtLaunch: true
