---
"AWSTemplateFormatVersion": "2010-09-09"

Parameters:
  WindowsAmi:
    Type: String
  LinuxAmi:
    Type: String

Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        KeyName: allenflab4
        InstanceType: t3.micro
        SecurityGroupIds:
          - !ImportValue AllenMod5Sg
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: user
                Value: allen.fisher
              - Key: "stelligent-u-lesson"
                Value: "5"
  
  MyWindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref WindowsAmi
      AvailabilityZone: us-west-1a
      SubnetId: !ImportValue AllenLab5PublicSubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: "1"

  MyLinuxInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LinuxAmi
      AvailabilityZone: us-west-1a
      SubnetId: !ImportValue AllenLab5PublicSubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: "1"
