---
"AWSTemplateFormatVersion": "2010-09-09"

Resources:
  AllenVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "5"

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.43.0/24
      VpcId: !Ref AllenVPC
      AvailabilityZone: us-west-1a
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "5"

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.44.0/24
      VpcId: !Ref AllenVPC
      AvailabilityZone: us-west-1a
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "5"

  AllenIG:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "5"

  IgAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref AllenIG
      VpcId: !Ref AllenVPC

  AllenRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "5"
      VpcId: !Ref AllenVPC

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "5"
      VpcId: !Ref AllenVPC

  AllenRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref AllenRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref AllenIG

  NatRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref AllenNatGateway

  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref AllenRouteTable
      SubnetId: !Ref PublicSubnet

  NatRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet

  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  AllenNatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref PublicSubnet

  PublicNacl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "5"
      VpcId: !Ref AllenVPC

  PublicNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 47.158.220.84/32
      Egress: false
      NetworkAclId: !GetAtt PublicNacl.Id
      PortRange:
        From: 22
        To: 22
      Protocol: 6
      RuleAction: allow
      RuleNumber: 200

  PrivateNacl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "5"
      VpcId: !Ref AllenVPC

  PrivateNaclEntrySsh:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 10.0.43.0/24
      Egress: false
      NetworkAclId: !GetAtt PrivateNacl.Id
      PortRange:
        From: 22
        To: 22
      Protocol: 6
      RuleAction: allow
      RuleNumber: 200

  PrivateNaclEntryPing:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 10.0.43.0/24
      Egress: false
      NetworkAclId: !GetAtt PrivateNacl.Id
      PortRange:
        From: 8
        To: 0
      Protocol: 1
      Icmp:
        Code: -1
        Type: 8
      RuleAction: allow
      RuleNumber: 201

  PrivateNaclEntryHttp:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 10.0.43.0/24
      Egress: false
      NetworkAclId: !GetAtt PrivateNacl.Id
      PortRange:
        From: 80
        To: 80
      Protocol: 6
      RuleAction: allow
      RuleNumber: 202

  PrivateNaclEntryEgress:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 10.0.43.0/24
      Egress: true
      NetworkAclId: !GetAtt PrivateNacl.Id
      PortRange:
        From: -1
        To: -1
      Protocol: -1
      RuleAction: allow
      RuleNumber: 203
  
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allen F Lab 5 SG"
      GroupName: AllenFSg
      VpcId: !GetAtt AllenVPC.VpcId
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: 8
          ToPort: 0
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  VPCId:
    Description: "VPC ID for Allen Module 05"
    Value: !Ref AllenVPC
    Export:
      Name: AllenLab5VpcId
  PublicSubnetId:
    Description: "Public SubnetID for Allen Module 05"
    Value: !Ref PublicSubnet
    Export:
      Name: AllenLab5PublicSubnetId
  PrivateSubnetId:
    Description: "Private SubnetID for Allen Module 05"
    Value: !Ref PrivateSubnet
    Export:
      Name: AllenLab5PrivateSubnetId
  SecurityGroupId:
    Description: "Security Group for Allen Module 05"
    Value: !Ref MySecurityGroup
    Export:
      Name: AllenMod5Sg

