---
"AWSTemplateFormatVersion": "2010-09-09"

Parameters:
  MyCidrBlock:
    Type: String

Resources:
  AllenVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref MyCidrBlock
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "4"
        - Key: "stelligent-u-lab"
          Value: "4.1.1"
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.43.0/24
      VpcId: !Ref AllenVPC
      AvailabilityZone: us-west-1a
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "4"
        - Key: "stelligent-u-lab"
          Value: "4.1.1"

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.44.0/24
      VpcId: !Ref AllenVPC
      AvailabilityZone: us-west-1a
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "4"
        - Key: "stelligent-u-lab"
          Value: "4.1.7"

  AllenIG:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "4"
        - Key: "stelligent-u-lab"
          Value: "4.1.2"

  IgAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref AllenIG
      VpcId: !Ref AllenVPC

  AllenRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "4"
        - Key: "stelligent-u-lab"
          Value: "4.1.2"
      VpcId: !Ref AllenVPC

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: user
          Value: allen.fisher
        - Key: "stelligent-u-lesson"
          Value: "4"
        - Key: "stelligent-u-lab"
          Value: "4.1.7"
      VpcId: !Ref AllenVPC

  AllenRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref AllenRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref AllenIG

  NatRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref AllenNatGateway

  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref AllenRouteTable
      SubnetId: !Ref PublicSubnet

  NatRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet

  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  AllenNatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref PublicSubnet

Outputs:
  VPCId:
    Description: "VPC ID for Allen Module 04"
    Value: !Ref AllenVPC
    Export:
      Name: AllenLab4VPCId
  SubnetId:
    Description: "SubnetID for Allen Module 04"
    Value: !Ref PublicSubnet
    Export:
      Name: AllenLab4SubnetId
  PrivateSubnetId:
    Description: "Private SubnetID for Allen Module 04"
    Value: !Ref PrivateSubnet
    Export:
      Name: AllenLab4PrivateSubnetId
