---
AWSTemplateFormatVersion: "2010-09-09"

# Parameters:
#   IamUser:
#     Type: "String"

Resources:
  MyIAMManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Read Only Policy for S3 Buckets"
      ManagedPolicyName: "ReadOnlyS3"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "S3:Get*"
              - "S3:List*"
            Resource: "*"
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: "{{resolve:ssm:/allen.fisher/UserName:1}}"
      ManagedPolicyArns:
        - !Ref MyIAMManagedPolicy

Outputs:
  PolicyArn:
    Description: "ARN for the S3 Managed Policy"
    Value: !Ref MyIAMManagedPolicy
    Export:
      Name: S3ReadOnlyPolicy
