---
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt-get update -y
      - apt-get install -y uuid-runtime
      - pip install cfn-lint

  build:
    commands:
      - echo "Validating CFN Template"
      - cfn-lint 12-codepipeline/bucket.yaml
